# Generated by Django 4.2.11 on 2024-04-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_person_age_person_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(default='https://memepedia.ru/wp-content/uploads/2024/04/enot-pedro-pedro-pedro-768x566.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
