# Generated by Django 4.2.11 on 2024-04-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='middlename',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
