# Generated by Django 4.2.11 on 2024-04-30 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_student_middlename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1 класс'), (2, '2 класс'), (3, '3 класс'), (4, '4 класс'), (5, '5 класс'), (6, '6 класс'), (7, '7 класс'), (8, '8 класс'), (9, '9 класс'), (10, '10 класс'), (11, '11 класс')], default=1, max_length=2),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20)),
                ('surname', models.CharField(blank=True, default='', max_length=20)),
                ('middlename', models.CharField(blank=True, default='', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date(2024, 4, 30))),
                ('subject', models.ManyToManyField(blank=True, choices=[('Биология', 'Биология'), ('География', 'География'), ('Иностранный язык', 'Иностранный язык'), ('Информатика', 'Информатика'), ('История', 'История'), ('Математика', 'Математика'), ('ОБЖ', 'ОБЖ'), ('Обществознание', 'Обществознание'), ('Русский язык', 'Русский язык'), ('Физика', 'Физика'), ('Физическая культура', 'Физическая культура'), ('Химия', 'Химия')], default='', to='core.student')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
    ]
