# Generated by Django 4.2.11 on 2024-04-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_student_options_alter_student_grade_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(blank=True, choices=[('Биология', 'Биология'), ('География', 'География'), ('Иностранный язык', 'Иностранный язык'), ('Информатика', 'Информатика'), ('История', 'История'), ('Математика', 'Математика'), ('ОБЖ', 'ОБЖ'), ('Обществознание', 'Обществознание'), ('Русский язык', 'Русский язык'), ('Физика', 'Физика'), ('Физическая культура', 'Физическая культура'), ('Химия', 'Химия')], default='', max_length=20),
        ),
    ]
